version: '3'

services:
  
  postgres:
    image:  'postgres:latest'
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=crunchbang
      - POSTGRES_USER=postgres
      - POSTGRES_DB=demo
  
  rabbitmq:
    image:  'rabbitmq:latest'
    ports:
      - "5672:5672"

  rabbitmq-management:
    image:  'rabbitmq:3-management'
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest


  async-worker:
    image: deviceapp
    command: bash -c "./wait-for-it.sh rabbitmq:5672 -- celery -A deviceapp.app worker -l INFO"
    depends_on:
      - postgres
      - rabbitmq

  web:
    build: .
    image: deviceapp
    command: bash -c "./wait-for-it.sh postgres:5432 -- python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - async-worker