# Generated by Django 2.1 on 2019-05-16 10:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['first_name', 'email', 'last_name'], name='employee_em_first_n_80a5ef_idx'),
        ),
    ]
