# Generated by Django 2.1 on 2019-05-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
