# Generated by Django 2.1 on 2019-05-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20190516_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
